name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    ##- name: Build
      ##run: dotnet pack --configuration Release -o output
    - name: Publish NuGet
      uses: rohith/publish-nuget@v2.2.1
      with:
        PROJECT_FILE_PATH: Useful.String.Extensions/Useful.String.Extensions.csproj
        TAG_COMMIT: false
        NUGET_KEY: ${{ secrets.NugetAPIKey }}
    - name: asd1
      run: pwd #find / -name "*.nupkg" art 2>/dev/null
    - name: asd2
      run: ls #find / -name "*.nupkg" art 2>/dev/null
