name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    ##- name: Build
      ##run: dotnet pack --configuration Release -o output
    #- name: Publish NuGet
      #uses: rohith/publish-nuget@v2.2.1
      #with:
        #PROJECT_FILE_PATH: Useful.String.Extensions/Useful.String.Extensions.csproj
        #TAG_COMMIT: false
        #NUGET_KEY: ${{ secrets.NugetAPIKey }}

  post_build:
    runs-on: ubuntu-latest
    steps:
      - name: asd1
        run: Useful.String.Extensions/Useful.String.Extensions.csproj | grep -Po '(?<=Version>).*(?=</Version>)'
      - name: asd2
        run: Useful.String.Extensions/Useful.String.Extensions.csproj | grep -Pzo '(?<=PackageReleaseNotes>)(.|\n)*(?=</PackageReleaseNotes>)'
      - name: asd3
        run: ls
      - name: asd3
        run: ls Useful.String.Extensions
