name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101

    - name: Build
      run: dotnet pack --configuration Release -o output

    #- name: Publish NuGet
      #uses: rohith/publish-nuget@v2.2.1
      #with:
        ## Filepath of the project to be packaged, relative to root of repository
        #PROJECT_FILE_PATH: Useful.String.Extensions/Useful.String.Extensions.csproj
        ## Whether to create a tag when there's a version change
        #TAG_COMMIT: false
        #NUGET_KEY: ${{ secrets.NugetAPIKey }}


    - id: get-version-number
      name: Get version number
      run: cat Useful.String.Extensions/Useful.String.Extensions.csproj | grep -Po '(?<=Version>).*(?=</Version>)' #echo ::set-env name=GITHUB_SHA_SHORT::$(cat Useful.String.Extensions/Useful.String.Extensions.csproj | grep -Po '(?<=Version>).*(?=</Version>)')

    - name: test
      run: echo ${{steps.get-version-number.outputs.result}}
